### ISSUE TITLE
非线程安全，有时候会崩溃在

### ISSUE THREAD

**Issue by KrisLee** [MQCCoder/XYIAPKit#1]
调用 self.successBlock(products, invalidProductIdentifiers)时候会崩溃

- (void)productsRequest:(SKProductsRequest *)request didReceiveResponse:(SKProductsResponse *)response
{
    NSLog(@"products request received response");
    NSArray *products = [NSArray arrayWithArray:response.products];
    NSArray *invalidProductIdentifiers = [NSArray arrayWithArray:response.invalidProductIdentifiers];
    
    for (SKProduct *product in products)
    {
        NSLog(@"received product with id %@", product.productIdentifier);
        if (_addProductBlock) {
            _addProductBlock(product);
        }
    }
    
    [invalidProductIdentifiers enumerateObjectsUsingBlock:^(NSString *invalid, NSUInteger idx, BOOL *stop) {
        NSLog(@"invalid product with id %@", invalid);
    }];
    
    if (self.successBlock)
    {
        self.successBlock(products, invalidProductIdentifiers);
    }

**Comment by mqc123450** [comment]
能看一下错误log吗？这个回调应该是在主线程，线程应该是安全的啊

**Comment by KrisLee** [comment]
自己创建的UIWindow，如何调用支付。不一定是在主线程

**Comment by KrisLee** [comment]
有多个UIWindow的时候

**Comment by mqc123450** [comment]
不太理解UIWindow跟支付的线程有什么关系？
