### ISSUE TITLE
为什么一直出现不能连接到itune store账户呢

### ISSUE THREAD

**Issue by woshicainiaohahaha** [MQCCoder/XYIAPKit#2]
transaction------<SKPaymentTransaction: 0x2805a43a0>/n error------Error Domain=SKErrorDomain Code=0 "无法连接到 iTunes Store" UserInfo={NSLocalizedDescription=无法连接到 iTunes Store}

**Comment by mqc123450** [comment]
苹果服务器问题吧，一般苹果发布会或者技术大会前后容易出现这种问题，可以找个其他时间段试试

**Comment by woshicainiaohahaha** [comment]
已经解决了，创建测试账号的时候后面apppay没有认证，今天突然就好了，谢谢。
