### ISSUE TITLE
'YYModel.h' file not found

### ISSUE THREAD

**Issue by lightlosy** [MQCCoder/XYIAPKit#9]
cloneXYIAPKit后在工程add file to project，然后
XYIAPKit/Receipt/iTunesReceiptVerify/XYStoreiTunesReceiptVerifier.m里面
#import "YYModel.h"报错 "YYModel.h file not found"。
需要自己下载YYKit吗？

**Comment by MQCCoder** [comment]
不用的，自己会引入YYModel的

**Comment by lightlosy** [comment]
解决了，新手问题，pod install后，要重新打开工程目录下的workspace文件，而不是xcodeproj文件
